### ISSUE TITLE
Invalid NuGet Version String: NETSDK1018

### ISSUE THREAD

**Issue by tom-corwin** [tom-corwin/tcdfx#17]
When CI builds are ran, they fail because apparently `1.0.0-20190603.01` is not a valid version string.

I don't know why this isn't valid. If anyone has any ideas, please let me know, because I'm really stumped with this one.

**Note**: This applies to the `code-rewrite` branch.

Command Ran:

```
dotnet build D:\a\1\s\sources\TCDFx.Core\TCDFx.Core.csproj -c Debug --force --no-dependencies --nologo --no-restore --version-suffix 20190603.01
```

Output:

```
D:\a\_tool\dotnet\sdk\3.0.100-preview5-011568\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets(157,5): message NETSDK1057: You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview [D:\a\1\s\sources\TCDFx.Core\TCDFx.Core.csproj]
D:\a\_tool\dotnet\sdk\3.0.100-preview5-011568\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.GenerateAssemblyInfo.targets(160,5): error NETSDK1018: Invalid NuGet version string: '1.0.0-20190603.01'. [D:\a\1\s\sources\TCDFx.Core\TCDFx.Core.csproj]

Build FAILED.

D:\a\_tool\dotnet\sdk\3.0.100-preview5-011568\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.GenerateAssemblyInfo.targets(160,5): error NETSDK1018: Invalid NuGet version string: '1.0.0-20190603.01'. [D:\a\1\s\sources\TCDFx.Core\TCDFx.Core.csproj]
    0 Warning(s)
    1 Error(s)
```

**Comment by tom-corwin** [comment]
This seems to only affect the `Debug` configuration.

**Comment by tom-corwin** [comment]
I *might* have a fix for this in the next commit.. I hope. Semantic Versions are extremely specific, and I think it's the `.`in the version suffix. Attempting to replace it with a hyphen.

**Comment by tom-corwin** [comment]
Fixed with https://github.com/tom-corwin/tcdfx/commit/5fb6976a4f18217fdaff73775bc03d6f48e1034e

**Comment by jsblock78** [comment]
@tom-corwin  I stumbled across your issue while searching NETSDK1018.

I think the zero here: 1.0.0-20190603.**0**1 was more the problem than the `.`.

Having version suffix (pre-release version) has these rules:

A pre-release version MAY be denoted by appending a hyphen and a series of dot separated identifiers immediately following the patch version. Identifiers MUST comprise only ASCII alphanumerics and hyphen [0-9A-Za-z-]. Identifiers MUST NOT be empty. **Numeric identifiers MUST NOT include leading zeroes.**

Personally, I was using this:

$([System.DateTime]::Now.ToString(yyyyMMdd.HHmmss))

Which would break builds that would execute between midnight and 1AM.

**Comment by tom-corwin** [comment]
Ahh, that would make more sense. I didnt realize that the leading 0 was a problem. 

It seems i missed the part about the version string being comprised of dot-separated identifiers that start with a non-0 character. 

Thanks for pointing that out, or i wouldve probably never figured it out if i ran into it again.
